pkgdir: ${capsula.debian.packageName}_${version.version}
dockerhub_image: sfuhrm/capsula:debian_stretch
dockerhub_url: https://hub.docker.com/r/sfuhrm/capsula-debian-stretch/
image_label: capsula-debian-stretch
use_dockerhub: true
debian_destdir: debian/${capsula.debian.packageName}/
<#if capsula.debian.architecture == 'all'>
debian_arch: all
<#elseif capsula.debian.architecture == 'any'>
debian_arch: amd64 <#-- TBD: fixed mapping sucks here -->
</#if>
