language: java
env:
  global:
    - VERSION: 0.1.4-SNAPSHOT
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
#install: mvn install -Dgpg.skip
#
# Build stages Beta.
# See: https://docs.travis-ci.com/user/build-stages/
jobs:
  include:
    # compile the sources
    - stage: compile
      script: mvn --batch-mode clean install -Dgpg.skip
    # This will run certain combinations of parameters and configs.
    # Note that it because of missing docker it can only run to the stage PREPARE.
    - stage: smoketest
      script:
      # just validate the descriptor
      - java -jar target/capsula-$VERSION-jar-with-dependencies.jar -c -f capsula.yaml -o out
      # read descriptor
      - java -jar target/capsula-$VERSION-jar-with-dependencies.jar -f capsula.yaml -o out -stop-after READ_DESCRIPTOR
      # build templates
      - java -jar target/capsula-$VERSION-jar-with-dependencies.jar -f capsula.yaml -o out -stop-after PREPARE
      # build templates, this time parallel
      - java -jar target/capsula-$VERSION-jar-with-dependencies.jar -f capsula.yaml -o out -parallel -stop-after PREPARE
      # build templates, google-java-format, this time parallel
      - java -jar target/capsula-$VERSION-jar-with-dependencies.jar -f examples/google-java-format.yaml -o out -parallel -stop-after PREPARE
stages:
  - compile
  - test
  - smoketest
