language: java
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
install: mvn install -Dgpg.skip
jobs:
  include:
    # compile the sources
    - stage: compile
      script: mvn clean install -Dgpg.skip
    # this will start doing an archive for itself but stop after expanding the templates
    - stage: test
      script: java -jar target/capsula-0.1.3-SNAPSHOT-jar-with-dependencies.jar -f capsula.yaml -o out -stop-after PREPARE
    # Release on GitHub, see https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
stages:
  - compile
  - test
  - GitHub Release
